services:
  # 1. The Node/Express Backend
  - type: web
    name: mern-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false 
      - key: NODE_ENV
        value: production

 # 2. The React Frontend
  - type: web          # <--- Change this to 'web'
    name: mern-frontend
    runtime: static    # <--- Add this line!
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routingRules:
      - route: /*
        rewritePath: /index.html